
services:
  #todo -  Servicio de PostgreSQL
  postgres-db:
    image: postgres:15.3
    restart: always

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    # Donde guardar los datos de mi base de datos
    volumes:
      - ./postgres:/var/lib/postgresql/data

    # Puertos de la base de datos - 5432 Puerto por defecto de PostgreSQL
    ports:
      - "5433:5432"